### ISSUE TITLE
Windows error running "python setup.py develop"

### ISSUE THREAD

**Issue by 4738259** [raisimTech/raisimLib#425]
Hello, thank you for the great simulator.

I have a problem when I try "python setup.py develop" on cmd.
The message says "No such file or directory", but I made sure that eigen.h and rsg_anymal.vcxproj, the two files mentioned by the error message below, were on the right path.

I want to know what the problem is.

```
C:\Users\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch>python setup.py develop
running develop
running egg_info
writing raisim_gym_torch.egg-info\PKG-INFO
writing dependency_links to raisim_gym_torch.egg-info\dependency_links.txt
writing requirements to raisim_gym_torch.egg-info\requires.txt
writing top-level names to raisim_gym_torch.egg-info\top_level.txt
reading manifest file 'raisim_gym_torch.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'raisim_gym_torch.egg-info\SOURCES.txt'
running build_ext
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- pybind11 v2.9.0
-- raisim:
--   Version: 1.1.6
--   Includes: C:/Users/hj/.raisim/RAISIM_project/raisimLib/raisim/win32/include
--   Libraries: raisim::raisimPng;raisim::raisimODE;raisim::raisimMine;raisim::raisim
raisim os win32
raisim arch
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/hj/.raisim/RAISIM_project/raisimLib/raisimGymTorch/build/temp.win-amd64-3.8/Release
.NET Framework용 Microsoft (R) Build Engine 버전 16.11.2+f32259642
Copyright (C) Microsoft Corporation. All rights reserved.

cl : 명령줄 warning D9002: 알 수 없는 '-fopenmp' 옵션을 무시합니다. [C:\Users\hj\.raisim\RAISIM_project\raisimLib
\raisimGymTorch\build\temp.win-amd64-3.8\Release\rsg_anymal.vcxproj]
cl : 명령줄 warning D9002: 알 수 없는 '-fPIC' 옵션을 무시합니다. [C:\Users\hj\.raisim\RAISIM_project\raisimLib\ra
isimGymTorch\build\temp.win-amd64-3.8\Release\rsg_anymal.vcxproj]
cl : 명령줄 warning D9002: 알 수 없는 '-O3' 옵션을 무시합니다. [C:\Users\hj\.raisim\RAISIM_project\raisimLib\rais
imGymTorch\build\temp.win-amd64-3.8\Release\rsg_anymal.vcxproj]
cl : 명령줄 warning D9002: 알 수 없는 '-flto' 옵션을 무시합니다. [C:\Users\hj\.raisim\RAISIM_project\raisimLib\ra
isimGymTorch\build\temp.win-amd64-3.8\Release\rsg_anymal.vcxproj]
cl : 명령줄 warning D9002: 알 수 없는 '-mno-avx2' 옵션을 무시합니다. [C:\Users\hj\.raisim\RAISIM_project\raisimLi
b\raisimGymTorch\build\temp.win-amd64-3.8\Release\rsg_anymal.vcxproj]
  raisim_gym.cpp
C:/Users/hj/.raisim/RAISIM_project/raisimLib/raisimGymTorch/thirdParty/pybind11/include\pybind11/e
igen.h(30,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Eigen/Core': No such file or directory [C:\Use
rs\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch\build\temp.win-amd64-3.8\Release\rsg_anymal.
vcxproj]
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    setup(
  File "C:\Users\hj\miniconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\hj\miniconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\hj\miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\hj\miniconda3\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\hj\miniconda3\lib\site-packages\setuptools\command\develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\hj\miniconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\hj\miniconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.build_extension(ext)
  File "setup.py", line 66, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "C:\Users\hj\miniconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
```

**Comment by jhwangbo** [comment]
The error is ``C:/Users/hj/.raisim/RAISIM_project/raisimLib/raisimGymTorch/thirdParty/pybind11/include\pybind11/e
igen.h(30,10): fatal error C1083: 포함 파일을 열 수 없습니다. 'Eigen/Core': No such file or directory ``
I am not sure why it happens, but copy the ``raisimLib\thirdParty\Eigen3\include\eigen3\Eigen`` directory to ``C:/Users/hj/.raisim/RAISIM_project/raisimLib/raisimGymTorch/thirdParty/pybind11/include\pybind11/``. This should solve the issue

**Comment by 4738259** [comment]
Thank you for reply. But the problem remains the same.

As your advice, I tried these three things:
1. I copied the folder "Eigen" in 
C:\Users\hj\.raisim\RAISIM_project\raisimLib\thirdParty\Eigen3\include\eigen3 
to 
C:\Users\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch\thirdParty\pybind11\include\pybind11 
by ctrl+c and ctrl+v. But the command "python setup.py develop" didn't work.
2. I deleted the copied folder from 1. And I copied again by commanding 
`copy C:\Users\hj\.raisim\RAISIM_project\raisimLib\thirdParty\Eigen3\include\eigen3\Eigen C:\Users\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch\thirdParty\pybind11\include\pybind11`
on cmd.
Then all files in the folder "Eigen" except the folder "src" copied to folder "pybind11". But the command "python setup.py develop" didn't work.
3. In addition to 2., I copied the folder "src" in the folder "Eigen" to "pybind11" by ctrl+c and ctrl+v. then tried "python setup.py develop".

In all three attempts above, the error message was exactly the same as the one I uploaded.

**Comment by jhwangbo** [comment]
C++ compiler should find an included file relative to its location. So if the `Core` file is in `Eigen` folder relative to `eigen.h` file, it should find it.

It is difficult for me to assess the issue because I cannot reporduce it.

**Comment by jhwangbo** [comment]
I pushed a commit. In that commit you will see the following line added 
`list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../thirdParty/Eigen3)`
This forces the raisimGymTorch to use the Eigen in the thirdParty folder.

Can you test if it works now? If your cmake cannot find `Eigen/Core`, it meas that it found a wrong Eigen package somewhere in your system.

**Comment by 4738259** [comment]
I don't know if I got it right. 

I opened 
`C:\Users\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch\CMakeLists.txt`
and added a line 
`list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../thirdParty/Eigen3)`.

Should I have changed 
`${CMAKE_CURRENT_SOURCE_DIR}/../thirdParty/Eigen3`
to
`C:\Users\hj\.raisim\RAISIM_project\raisimLib\thirdParty\Eigen3`
or something?

Anyway, I added a line 
`list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../thirdParty/Eigen3)`
to between 27th and 28th line of 
`C:\Users\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch\CMakeLists.txt`,
and tried 
`C:\Users\hj\.raisim\RAISIM_project\raisimLib\raisimGymTorch>python setup.py develop`
on cmd, but the same error message came up.

**Comment by 4738259** [comment]
Thank you for your help. Now, it works.

I tried `python setup.py develop` again. It didn't work on Windows PowerShell but it worked on cmd. 
It didn't work on both PowerShell and cmd at last time. I don't know why.

After that, I tried `python raisimGymTorch/env/envs/rsg_anymal/runner.py` on cmd. 
The error message says `AttributeError: module 'numpy' has no attribute 'bool'`.
I found that I have numpy version 1.24.1 but late version don't have `numpy.bool`. So I downgraded numpy to 1.21.2

Then, I tried `python raisimGymTorch/env/envs/rsg_anymal/runner.py` again. 
The error message says `TypeError: entry_points() got an unexpected keyword argument 'group'`.
I found that it is because of markdown and/or importlib-metadata. So I reinstalled both.

I tried `python raisimGymTorch/env/envs/rsg_anymal/runner.py` again, 
and finally it works.
